development:
  adapter: postgresql
  encoding: unicode
  database: newage_development
  host: localhost
  pool: 5
  username: newage
  password: newage

test:
  adapter: postgresql
  encoding: unicode
  database: newage_test
  host: localhost
  pool: 5
  username: newage
  password: newage